package com.jun.dao;

import com.jun.domain.Seller;
import com.jun.domain.SellerExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    long countByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int deleteByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int deleteByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int insertSelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    List<Seller> selectByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    Seller selectByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Seller record, @Param("example") SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int updateByExample(@Param("record") Seller record, @Param("example") SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int updateByPrimaryKeySelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Sep 27 09:31:33 CST 2018
     */
    int updateByPrimaryKey(Seller record);
}